### ISSUE TITLE
Use of incoming call UI only

### ISSUE THREAD

**Issue by gwendall** [ajith-ab/react-native-voip-call#1]
I am building an app in which I need to display the incoming call UI only, as a glorified notification. The calls themselves are handled in the app via webrtc. 

Is that a possible use case of your library ?

**Comment by ajith-ab** [comment]
@gwendall  yes !  below Android 8 version is possible while came a background state call app will open automatically other version are  shown a notification like Facebook Messenger. Android 8 later versions after Notification tap or Call answered button click then we will show custom screen

please look this method and navigate to Custom UI 

**App is in Background or Killed in Android**

```javascript
RNVoipCall.getInitialNotificationActions().then(data=>{
  //Navigate to Custom Call Screen
})
 .catch(e=>console.log(e)); 
```

**Events in handle Foreground**

```javascript
    RNVoipCall.onCallAnswer(data => {
  //Navigate to Custom Call Screen
          console.log(data);
    });

    //app open Automatically when Call recived
    RNVoipCall.onCallOpenAppEvent(event => {
  //Navigate to Custom Call Screen
    
    });
    // on click call Notification
    RNVoipCall.onCallNotificationOpen(event => {
       //Navigate to Custom Call Screen
    });


```

In IOS this plugin Has no Solution. Because IOS App not invoke to open Automatically when pushKit  Notification came but App in Foreground.  We should use Custom Call Screen

```javascript
import RNVoipCall, { RNVoipPushKit } from 'react-native-voip-call';

       //On Remote Push notification Recived in Forground
       RNVoipPushKit.RemotePushKitNotificationReceived((notification)=>{
           //Navigate to Custom Call Screen
       });

```

Thanks 
Ajith A B

**Comment by OguzEkinci** [comment]
> @gwendall yes ! below Android 8 version is possible while came a background state call app will open automatically other version are shown a notification like Facebook Messenger. Android 8 later versions after Notification tap or Call answered button click then we will show custom screen
> 
> please look this method and navigate to Custom UI
> 
> **App is in Background or Killed in Android**
> 
> ```js
> RNVoipCall.getInitialNotificationActions().then(data=>{
>   //Navigate to Custom Call Screen
> })
>  .catch(e=>console.log(e)); 
> ```
> 
> **Events in handle Foreground**
> 
> ```js
>     RNVoipCall.onCallAnswer(data => {
>   //Navigate to Custom Call Screen
>           console.log(data);
>     });
> 
>     //app open Automatically when Call recived
>     RNVoipCall.onCallOpenAppEvent(event => {
>   //Navigate to Custom Call Screen
>     
>     });
>     // on click call Notification
>     RNVoipCall.onCallNotificationOpen(event => {
>        //Navigate to Custom Call Screen
>     });
> ```
> 
> In IOS this plugin Has no Solution. Because IOS App not invoke to open Automatically when pushKit Notification came but App in Foreground. We should use Custom Call Screen
> 
> ```js
> import RNVoipCall, { RNVoipPushKit } from 'react-native-voip-call';
> 
>        //On Remote Push notification Recived in Forground
>        RNVoipPushKit.RemotePushKitNotificationReceived((notification)=>{
>            //Navigate to Custom Call Screen
>        });
> ```
> 
> Thanks Ajith A B

how do i listen onCallAnswer or any other func with addlistener
