### ISSUE TITLE
Unable to compile release build

### ISSUE THREAD

**Issue by Yatanvesh** [ajith-ab/react-native-voip-call#4]
Here is the gradle log. I've tried a couple of things but couldn't get the build to work

> Task :react-native-voip-call:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-voip-call:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/master/.gradle/caches/transforms-2/files-2.1/37abfcfbc82b67ac6e52fc7a4652058d/appcompat-1.0.2/res/values-v28/values-v28.xml:5:5-8:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     /home/master/.gradle/caches/transforms-2/files-2.1/37abfcfbc82b67ac6e52fc7a4652058d/appcompat-1.0.2/res/values-v28/values-v28.xml:9:5-12:13: AAPT: error: resource android:attr/dialogCornerRadius not found.
         
     /home/master/.gradle/caches/transforms-2/files-2.1/1c57a05a5d283c9a708b173ed536b993/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
         
     /home/master/.gradle/caches/transforms-2/files-2.1/1c57a05a5d283c9a708b173ed536b993/core-1.0.1/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

**Comment by Yatanvesh** [comment]
Ive found that upgrading the compile and target sdk version in build.gradle file of this library fixes the issue. I shall make a PR shortly

**Comment by ajith-ab** [comment]
In New Version fixed this issue

Thanks & Regards 
Ajith A B
