### ISSUE TITLE
Package not support for Android 12 & targerSdkVersion 31 and above

### ISSUE THREAD

**Issue by DeepikaSharma5** [ajith-ab/react-native-voip-call#47]
The backege have issue related to PendingIntent which make the package won't support for SDK version more than 30

Fix it or provide an alternative package @sadaf2605 @Yatanvesh @ajith-ab

**Comment by devmurarihardik** [comment]
yes, i am also getting the same issue regarding the Pendingintent. please provide any solution.

**Comment by devmurarihardik** [comment]
@DeepikaSharma5 thank you for resolving the issue. it's work's for me.

@DeepikaSharma5 has created a new package with the solution please try it.

https://www.npmjs.com/package/react-native-voips-calls
