### ISSUE TITLE
Adding it to a project with google signin configured breaks google sign in.

### ISSUE THREAD

**Issue by Yatanvesh** [ajith-ab/react-native-voip-call#7]
I added react-native-voip-call to my project. Merely adding it breaks signIn functionality and app crashes.
https://github.com/react-native-community/google-signin

**Comment by Yatanvesh** [comment]
This is the log that we get when the app crashes
java.lang.runtimeexception failure delivering result to MainActivity attempt to invoke virtual method in java.lang.hashcode on null object reference

**Comment by sadaf2605** [comment]
it should fix this problem. https://github.com/ajith-ab/react-native-voip-call/pull/8

**Comment by Yatanvesh** [comment]
Thank you, i will try this

**Comment by ajith-ab** [comment]
@sadaf2605  Fixed in new Version

Thanks & Regards
Ajith A B
